export const ROUTES = {
  HOME: 'Home',
  PRODUCT: 'Product',
  TRAINING_WORKSHOPS: 'Training Workshops',
  TRAINING_WORKSHOPS_DETAILS: 'Training Workshops Details',
  FEEDBACK: 'Feedback',
  SETTING: 'Settings',
  FEEDBACK_MODAL: 'FeedbackModal',
  DECOR_GALLERY: 'Decor Gallery',
  ABOUT_US: 'About Us',
  ITEMS_COMPONENT: 'ItemsComponent',
  ITEM_DETAILS: 'ItemDetails',
  CART: 'Cart',
  ORDER: 'ORDER',
  EDIT_PROFILE: 'EditProfile',
  VIEW_PROFILE: 'ViewProfile',
  ADMIN: 'Admin',
  ITEM_LIST_COMPONENT: 'ItemListComponent',
  ITEM_ADD_COMPONENT: 'ItemAddComponent',
  CATEGORY_ADD_COMPONENT: 'CategoryAddComponent',
  ORDER_LIST_COMPONENT: 'OrderListComponent',
  ORDER_DETAILS: 'OrderDetails',
  PENDING_ORDER_LIST: 'PendingOrderListComponent',
  PENDING_ORDER_DETAILS: 'PendingOrderDetails',
};
